### ISSUE TITLE
Will this work on the ZYBO board?

### ISSUE THREAD

**Issue by sunnystormy** [furkanturan/lowrisc-zed#10]
I noticed that you have this Zedboard codebase here, and I want to ask if this will deploy onto the ZYBO board as well? (https://store.digilentinc.com/zybo-zynq-7000-arm-fpga-soc-trainer-board/)

Both have Zynq FPGAs on them, but obviously a different board layout. Please let me know!

Thank you!

**Comment by furkanturan** [comment]
I didn't try, but it should work. I suppose what you only need to do is to change the target board configuration to Zybo. In this example code, the target board is set twice to Zedboard, once in make_project.tcl, and the second is in sed_bd.tcl. Either you can work changing them there, or you can create the project for Zed board, open it in Vivado, and later change the target on Vivado.

Also be careful with the resource you have available in Zybo. I think the design will still fit, but may result into high utilisation, in which case you may prefer getting rid of some features you will not use.

Regards,

**Comment by sunnystormy** [comment]
Thank you for the feedback! I'm happy to hear that changing the target is a trivial matter. I will look into this, then, and see how much stress is put on the board. Cheers!
